stages:
  - mirror

variables:
  DOCKER_REGISTRY: "docker.io"
  DOCKER_IMAGE: "alpine:latest"

mirror:
  stage: mirror
  before_script:
    - apk add --no-cache git openssh-keygen openssh-client-default
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - rm -Rf git_sync
    - mkdir git_sync
    - cd git_sync
    - git init
    - git remote add origin $CI_REPOSITORY_URL
    - git remote add upstream $GITHUB_REPO_URL
    - git fetch upstream
    - git reset --hard upstream/$CI_DEFAULT_BRANCH
    - git push -f "https://${GITLAB_USER_LOGIN}:${ACCESS_TOKEN}@${CI_REPOSITORY_URL#*@}" "HEAD:${CI_DEFAULT_BRANCH}"
  only:
    - schedules