stages:
  - mirror

variables:
  DOCKER_REGISTRY: "docker.io"
  DOCKER_IMAGE: "alpine:latest"

mirror:
  stage: mirror
  before_script:
    - apk add --no-cache git openssh-keygen openssh-client-default
    - apk add --no-cache curl
    - apk add --no-cache gnupg
    - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /etc/apk/keys/githubcli-archive-keyring.gpg
    - echo "https://cli.github.com/packages/ stable main" | tee github-cli.list > /dev/null
    - mv github-cli.list /etc/apk/repositories
    - apk update
    - apk add gh
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - TIMESTAMP=$(date +%s)
    - DIR_NAME="git_sync_$TIMESTAMP"
    - mkdir -p $DIR_NAME
    - cd $DIR_NAME
    - git init
    - git remote add origin $CI_REPOSITORY_URL
    - git remote add upstream $GITHUB_REPO_URL
    - git fetch upstream
    - git reset --hard upstream/$CI_DEFAULT_BRANCH
    - git push -f "https://${GITLAB_USER_LOGIN}:${ACCESS_TOKEN}@${CI_REPOSITORY_URL#*@}" "HEAD:${CI_DEFAULT_BRANCH}"
    - echo $GITHUB_TOKEN | gh auth login --with-token
    - for pr in $(gh pr list --state open --json number --jq '.[].number'); do
        gh pr checkout $pr;
        git push -f "https://${GITLAB_USER_LOGIN}:${ACCESS_TOKEN}@${CI_REPOSITORY_URL#*@}" "HEAD:pr-$pr";
      done
  only:
    - schedules
