name: Trigger Jenkins

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  inputs:
    machine:
      type: choice
      description: 'Run on RDHPCS Systems'
      required: true
      options:
        - Orion
        - Hercules
        - Hera
    case:
      type: choice
      description: Cases to run
      options:
        - C48_ATM
        - C48_S2SW
        - C48mx500_3DvarAOWCDA

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Jenkins
      run: | 
        curl -X POST https://jenkins.epic.oarcload.noaa.gov/job/global-workflow/job/EMC-Pipelines/build \
          --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} \
          --data-urlencode json='{"parameter": [{"name":"BRANCH", "value":"${{ github.event.pull_request.head.ref }}"},
                                                {"name":"CASE", "value":"${{ github.event.inputs.case }}"},
                                                {"name":"MACHINE", "value":"${{ github.event.inputs.machine }}"}
                                  ]}'