name: Trigger Jenkins

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Jenkins
      run: | 
        curl -X POST https://jenkins.epic.oarcload.noaa.gov/job/global-workflow/job/EMC-Pipelines/build \
          --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} \
          --data-urlencode json='{"parameter": [{"name":"BRANCH", "value":"${{ github.event.pull_request.head.ref }}"}]}'