name: Trigger Jenkins

on:
  workflow_dispatch:
    inputs:
      machine:
        type: choice
        description: 'Run on RDHPCS Systems'
        required: true
        options:
        - Orion-EMC
        - Hercules-EMC
        - Hera-EMC
      case:
        type: choice
        description: Cases to run
        options:
        - C48_ATM
        - C48_S2SW
        - C48mx500_3DvarAOWCDA
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Jenkins
      run: | 
        curl -X -L POST https://jenkins.epic.oarcloud.noaa.gov/job/global-workflow/job/EMC-Pipelines/job/PR-281/build \
          --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}
#          --data-urlencode json='{"parameter": [{"name":"machine", "value":"orion"},
#                                                {"name":"Node", "value":"${{ github.event.inputs.machine }}"}
#                                  ]}'